name: Build .NET MAUI Windows App

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI Windows Workload
        run: dotnet workload install maui-windows

      - name: Build application for Windows only
        run: dotnet build --configuration Release --framework net8.0-windows10.0.19041.0

      - name: Fail if build fails
        if: failure()
        run: exit 1
